Prevent expired timer beep between wake word and 'stop'
MycroftAI/mycroft-timer pull request #72
Opened 2020-06-29 12:25 UTC by krisgesling

This prevents the timer expired beeping from playing while the user is interacting with the device. 

Similar to the new process in mycroft-core, this will silence the beeping following a mic activation. 
- If no STT is returned it will resume beeping immediately. 
- If an utterance is received it will allow up to 8 seconds for a response to be made. This gives sufficient time for "stop", or even "what time is it".
- The expired timer beeping will resume following some dialog being spoken or after 8 seconds if no other activity takes place.

2020-06-30 22:37 UTC, devops-mycroft requested changes
Removed comment as it was posted under wrong user.

2020-06-30 22:39 UTC, chrisveilleux requested changes
This code is copied almost verbatim from the _restore_volume_after_record method in the AudioService class. It is also unnecessarily complex. I think we overuse nested functions in core. They have their place but this is a good example of how they can cause issues. I would like to see a re-think of how this functionality is implemented.

2020-07-01 05:19 UTC, forslund commented
@chrisveilleux I was going to use this template to implement this in the Spotify skill. Can you elaborate on the issues you mention?

2020-07-01 05:59 UTC, krisgesling commented
What do you think about shifting the `wait_for_speak` method to  `messagebus.client`, could generalize to:
```
def wait_for_message(self, type, timeout):
    ...
```

This would still require the nested `set_is_listening()` to be a callback for the event handlers but abstracts the most reusable code.

2020-07-01 05:59 UTC, krisgesling commented
is `messagebus.client` the right place?

2020-07-01 06:34 UTC, forslund commented
That may be a good addition to the messagebus client, doing a wait is quite common. It could be implemented now and then start to be used from 20.08.

After reading Chris's concerns I was thinking of a util class

so a skill creator could do:

```python
from mycroft.util import BusyDetector

[...]

   def initialize(self):
      self.muter = BusyDetector(self.bus, self.on_speech, self.on_done)

   def on_speech(self):
      if self.is_playing:
         self.pause()

   def on_done(self):
      if self.is_playing:
         self.resume()
```

(I personally like the inner functions here since they handle re-entrancy nicely and makes the functionality very self-contained)

2020-07-03 05:56 UTC, krisgesling commented
Hey @chrisveilleux as discussed, I think we need to provide a copy of the `wait_for_message` method in 20.2 Skills but they should be removed in 20.8.

I've added a #TODO as well as a ticket in the 20.8 Epic to do this.

2020-07-06 16:31 UTC, chrisveilleux approved these changes

2020-07-07 03:01 UTC, merged